[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    WiFi
    bblanchon/ArduinoJson @ ^7.0.4
    256dpi/MQTT @ ^2.5.2
    fastled/FastLED @ ^3.6.0
