[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    WiFi
    bblanchon/ArduinoJson @ ^6.21.3
    256dpi/MQTT @ ^2.5.1
